apiVersion: v1
kind: Service
metadata:
  name: assignment-app-service
spec:
  selector:
    app: assignment-app
  ports:
    - protocol: TCP
      port: 8080  # Port to be exposed by service
      targetPort: 8080  # Port in container
  type: NodePort  # Expose the service on a NodePort
