name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Debug Docker Username (without exposing sensitive details)
      - name: Debug Docker Username
        run: 'echo "Docker Username is set to: ''${{ secrets.DOCKER_USERNAME }}''"'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install
      
      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Debug Login Status
      - name: Verify Docker Login
        run: docker info | grep "Username"

      # Step 6: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}/assignment-app:latest" .
      
      # Step 7: Verify Docker Image
      - name: Verify Docker Image Exists
        run: docker images | grep "assignment-app"

      # Step 8: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/assignment-app:latest"
